
logs = [
  'SectionCrawler',
  'ArticleCrawler',
  'SourceLog',
  'LinksLog',
  'MultiArticle',
  'MultiSection',
  'WebsiteAPI',
  'articleLinksAPI',
  'TIME-LOG',
  'UpdateWebsite',
]

#---------- DEFINE SOCIAL MEDIA SITES ----------#
SOCIAL_MEDIA_KEYS = [
      "facebook",
      "twitter",
      "instagram",
      "youtube"
    ]

#---------- DEFINE SOCIAL MEDIA SITES ----------#
EXCLUDED_SECTION_KEYS = [
      'archives',
      'tag',
      'about',
      'happens',
      'privacy',
      'profile',
      'authors',
      'copyright',
      'contact',
      'contact us',
      'member',
      'rss',
      'author',
      'register',
      'login',
      'log in',
      'logout',
      'log out',
      'sign-up',
      'sign up',
      'sign in',
      'signup',
      'signin',
      'search',
      'register',
      'tos',
      'sitemap',
      'javascript',
      'jobs',
      'job opening',
      'info',
      'info desk',
      'redirect',
      'advertise',
      'user agreement',
      'policy',
      'newsletter',
      'terms and conditions',
      'sponsor',
      'account',
      'legal',
      'ccpa',
      'glossary',
      'donate',
      'mailto',
      'widgets'
    ]